---

# This playbooks should be running after provision-master.yml
# the reason for this is the fact that master should generate appropriate token to allow workers to join
# once such token has been generated, copy it into this playbooks and set as `k8_join_command` variable
# for example result of provision-master.yml :

  #TASK [k8 : Print command to join the cluster] **********************************
  #ok: [controller1] =>
  #  msg: kubeadm join 10.0.2.15:6443 --token 1lox2t.gjj4dwy0727hdpwe --discovery-token-ca-cert-hash sha256:e24b977769679cf2d383790651f3f513f37df79711b660589f86d6c7a2ac11ee


- name: Provision vagrant
  hosts: all
  vars:
    - k8_join_command:  "kubeadm join 10.0.99.1:6443 --token 0wijja.40ps9zd78b6mea1n --discovery-token-ca-cert-hash sha256:e262ec90db7cd7bcfc3679d2419d5e5639e7cafaf0d0a0a870038082c60fe178"
  become: yes
  roles:
    - common
    - docker_ce
    - k8
