---


- name: Provision vagrant
  hosts: all
  vars:
  # the  kubernetes_apiserver_advertise_address should match local ip configured in Vagrantfile for controller
    - kubernetes_apiserver_advertise_address: "10.0.99.1"
  become: yes
  roles:
    - common
    - docker_ce
    - k8

